# Generated by Django 4.1.2 on 2022-11-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngredientName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngredientClassDescription', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeClassDescription', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=20)),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeBook.ingredient')),
                ('RecipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeBook.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='RecipeClassID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeBook.recipe_class'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='IngredientClassID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeBook.ingredient_class'),
        ),
    ]
