# Generated by Django 4.1.2 on 2022-11-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBook', '0004_recipe_notes_recipe_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='RecipeClassID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeBook.recipe_class'),
        ),
    ]
